[package]
name = "wav_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.5"
winapi = {version = "0.3.9", features = ["mmdeviceapi", "combaseapi", "objbase", "audioclient"]}
